### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyBigWig#103]
Hi Devon,

Is there an option to get Python 3.8 support for pyBigWig? In the conda recipe I don't see any restrictions for this, and I wonder if it is enough to increase the build number to 1 to get a Bioconda to build also a Python 3.8 version.

Thanks and all the best,

Joachim

**Comment by dpryan79** [comment]
Bioconda hasn't migrated to python 3.8 yet, we expect that to happen a bit later in the summer.

**Comment by joachimwolff** [comment]
Ah alright, than I can stop my try to enable HiCExplorer for Python 3.8. Thanks for the information.
