### ISSUE TITLE
What is "None" bigwig signal values mean from pyBigWig bw.stats?

### ISSUE THREAD

**Issue by kac2053** [deeptools/pyBigWig#104]
Hi,

This isn't an issue but a question about pyBigWig bw.stats function. When extracting signal from bigwig, some signal values are labeled as "None". Do you happen know what "None" means.

I looked in IGV comparing the regions that have "None" signal versus the regions that have "0.0" signal values, and they both look the same.

Thank you.

**Comment by dpryan79** [comment]
If memory serves you'll get `None` if there are no entries in the bigWig file within the region specified.
