### ISSUE TITLE
Support for GCP bucket access?

### ISSUE THREAD

**Issue by francois-a** [deeptools/pyBigWig#107]
Hi,
Apologies if I missed this, but is there a way to read files directly from Google buckets?

**Comment by ghuls** [comment]
By using fsspec, it should be easy to add support for Google buckets, S3 buckets, ...:

> FSSPEC: Filesystem interfaces for Python
>
> Filesystem Spec (FSSPEC) is a project to unify various projects and classes to work with remote filesystems and file-system-like abstractions using a standard pythonic interface.
https://filesystem-spec.readthedocs.io/en/latest/

**Comment by dpryan79** [comment]
I really would like to avoid adding direct support for the various cloud storage mechanisms. Please use fuse or something like that to mount the buckets locally. That allows any tool to use data there and we don't then have to modify many thousands of packages.
