### ISSUE TITLE
Problem installing pyBigWig

### ISSUE THREAD

**Issue by hemantgujar** [deeptools/pyBigWig#109]
I have also gone through https://github.com/deeptools/pyBigWig/issues/9 
however could not resolve issue .. 

>pip install pyBigWig --target /project/gujar_71/gujar/hg1/software/Python-3.9.0/ --use-feature=2020-resolver

 ----------------------------------------

Collecting pyBigWig
  Using cached pyBigWig-0.3.17.tar.gz (64 kB)
Building wheels for collected packages: pyBigWig
  Building wheel for pyBigWig (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"'; __file__='"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pyuxs3vi
       cwd: /tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/
  Complete output (71 lines):
  /spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'classifier'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/__init__.py -> build/lib.linux-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/test.py -> build/lib.linux-x86_64-3.7/pyBigWigTest
  running egg_info
  writing pyBigWig.egg-info/PKG-INFO
  writing dependency_links to pyBigWig.egg-info/dependency_links.txt
  writing requirements to pyBigWig.egg-info/requires.txt
  writing top-level names to pyBigWig.egg-info/top_level.txt
  reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
  copying pyBigWigTest/test.bigBed -> build/lib.linux-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/test.bw -> build/lib.linux-x86_64-3.7/pyBigWigTest
  running build_ext
  building 'pyBigWig' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  C compiler: /spack/apps/gcc/8.3.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC

  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/libBigWig
  compile options: '-DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/site-packages/numpy/core/include -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -c'
  gcc: libBigWig/bwRead.cgcc: libBigWig/io.c

  gcc: libBigWig/bwStats.c
  gcc: libBigWig/bwWrite.c
  gcc: libBigWig/bwValues.c
  gcc: pyBigWig.c
  libBigWig/io.c:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  In file included from libBigWig/bigWig.h:1,
                   from libBigWig/bwRead.c:1:
  libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  In file included from libBigWig/bigWig.h:1,
                   from libBigWig/bwStats.c:1:
  libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  In file included from libBigWig/bigWig.h:1,
                   from libBigWig/bwValues.c:1:
  libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  In file included from libBigWig/bigWig.h:1,
                   from libBigWig/bwWrite.c:6:
  libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  In file included from libBigWig/bigWig.h:1,
                   from pyBigWig.h:3,
                   from pyBigWig.c:3:
  libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
   #include <curl/curl.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  error: Command "/spack/apps/gcc/8.3.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/site-packages/numpy/core/include -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -c libBigWig/bwRead.c -o build/temp.linux-x86_64-3.7/libBigWig/bwRead.o" failed with exit status 1
 
  ERROR: Failed building wheel for pyBigWig
  Running setup.py clean for pyBigWig
Failed to build pyBigWig
Installing collected packages: pyBigWig
    Running setup.py install for pyBigWig ... error
    ERROR: Command errored out with exit status 1:
     command: /spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"'; __file__='"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4do25bze/install-record.txt --single-version-externally-managed --home /tmp/pip-target-i_35toe3 --compile --install-headers /tmp/pip-target-i_35toe3/include/python/pyBigWig
         cwd: /tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/
    Complete output (71 lines):
    /spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'classifier'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/__init__.py -> build/lib.linux-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/test.py -> build/lib.linux-x86_64-3.7/pyBigWigTest
    running egg_info
    writing pyBigWig.egg-info/PKG-INFO
    writing dependency_links to pyBigWig.egg-info/dependency_links.txt
    writing requirements to pyBigWig.egg-info/requires.txt
    writing top-level names to pyBigWig.egg-info/top_level.txt
    reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
    copying pyBigWigTest/test.bigBed -> build/lib.linux-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/test.bw -> build/lib.linux-x86_64-3.7/pyBigWigTest
    running build_ext
    building 'pyBigWig' extension
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    C compiler: /spack/apps/gcc/8.3.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC

    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/libBigWig
    compile options: '-DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/site-packages/numpy/core/include -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -c'
    gcc: libBigWig/bwRead.cgcc: libBigWig/io.c
    gcc: libBigWig/bwStats.cgcc: libBigWig/bwWrite.c

    gcc: libBigWig/bwValues.c

    gcc: pyBigWig.c
    libBigWig/io.c:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    In file included from libBigWig/bigWig.h:1,
                     from libBigWig/bwStats.c:1:
    libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    In file included from libBigWig/bigWig.h:1,
                     from libBigWig/bwRead.c:1:
    libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    In file included from libBigWig/bigWig.h:1,
                     from libBigWig/bwValues.c:1:
    libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    In file included from libBigWig/bigWig.h:1,
                     from libBigWig/bwWrite.c:6:
    libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    In file included from libBigWig/bigWig.h:1,
                     from pyBigWig.h:3,
                     from pyBigWig.c:3:
    libBigWig/bigWigIO.h:2:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    error: Command "/spack/apps/gcc/8.3.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/lib/python3.7/site-packages/numpy/core/include -I/spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/include/python3.7m -c libBigWig/io.c -o build/temp.linux-x86_64-3.7/libBigWig/io.o" failed with exit status 1
 
ERROR: Command errored out with exit status 1: /spack/apps/linux-centos7-x86_64/gcc-8.3.0/python-3.7.6-dd2am3dyvlpovhd4rizwfzc45wnsajxf/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"'; __file__='"'"'/tmp/pip-install-47iztnjk/pybigwig_fa75be7a7938497198624c64806dd224/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4do25bze/install-record.txt --single-version-externally-managed --home /tmp/pip-target-i_35toe3 --compile --install-headers /tmp/pip-target-i_35toe3/include/python/pyBigWig Check the logs for full command output.

----------------------------------------

**Comment by hemantgujar** [comment]
ok figured it out somehow i was not using the wright curl directory.

**Comment by keh218** [comment]
I have this problem now too- how did you correct it if you remember? thanks :)

**Comment by dpryan79** [comment]
@keh218 I suggest installing with conda.
