### ISSUE TITLE
[bwGetOverlappingIntervalsCore] Got an error

### ISSUE THREAD

**Issue by wuzhaoqi1015** [deeptools/pyBigWig#117]
In [47]: bw = pyBigWig.open('hg19.100way.phyloP100way.bw')

In [48]: bw.stats('chr10', 90984924, 90984926)
[bwGetOverlappingIntervalsCore] Got an error
Out[48]: [None]

the reason is？

**Comment by wuzhaoqi1015** [comment]
[bwGetOverlappingIntervalsCore] Got an error

**Comment by dpryan79** [comment]
The most likely cause is running out of memory.

**Comment by wuzhaoqi1015** [comment]
> The most likely cause is running out of memory. There are actually 7 places in the code where this can be triggered, I hadn't foreseen needing to determine which was the root cause (mea culpa).

thanks
