### ISSUE TITLE
Open bw file for appending?

### ISSUE THREAD

**Issue by tncowart** [deeptools/pyBigWig#118]
I'd like to open an existing bigWig file and write new data to it without deleting the old data, but looking through the code I see that it's not supported. Is there a technical reason for this?

Thank you!

**Comment by dpryan79** [comment]
The format itself doesn't allow appending, unfortunately. The format is structured such that there are blocks of internal indices that would have to grow if you appended to a file, but they would then start overwriting data.

**Comment by tncowart** [comment]
Ah, bummer. Thank you for answering my question!
