### ISSUE TITLE
support for osx-arm64

### ISSUE THREAD

**Issue by phylyc** [deeptools/pyBigWig#127]
Hi!

I have a mac with an M1 chip. Installing pyBigWig is no problem via pip, though anaconda is smart enough to only check the osx-arm64 channels and tells me that it's not available. Currently, there is no build for this chip. 
Installing it via pip, when starting a python session and trying to import pyBigWig, I get the error

`>>> import pyBigWig`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen([...]/env/lib/python3.10/site-packages/pyBigWig.cpython-310-darwin.so, 0x0002): tried: '[...]/env/lib/python3.10/site-packages/pyBigWig.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`

Is there a plan to build for arm64? Or how can I build myself?
Thanks!

**Comment by dpryan79** [comment]
@phylyc It looks like you used a pip within an intel-python environment and then tried to run that using the arm-python. With the correct python in your path, you can prevent this with `python -m pip install ...the normal pip stuff...`.

**Comment by phylyc** [comment]
Thanks for the comment. I tried all possible things for a while, but it seems that the package in pip is indeed the intel version. The path to success was to download/clone the repo and use `python -m pip install .` in the repo within my miniconda environment.
