### ISSUE TITLE
numpy support broken in 0.3.18?

### ISSUE THREAD

**Issue by francois-a** [deeptools/pyBigWig#128]
Hi, is there an issue with numpy compatibility in 0.3.18? I'm seeing the following:
```
pip3 install pyBigWig=="0.3.17"
python3 -c "import pyBigWig; print(pyBigWig.numpy)"
1

pip3 install pyBigWig=="0.3.18"
python3 -c "import pyBigWig; print(pyBigWig.numpy)"
0
```
Thanks for looking into it.

**Comment by dpryan79** [comment]
It works fine, for example the one available via conda is compiled with support for numpy. Numpy needs to be installed before pyBigWig for that to work.
