### ISSUE TITLE
Create a BedGraph file using addEntries() throws segmentation fault

### ISSUE THREAD

**Issue by priesgo** [deeptools/pyBigWig#129]
Create a BedGraph file as shown below throws a Segmentation fault to me. Can someone else reproduce this error or may this be something with my local environment?

I am running pyBigWig 0.3.18 and Python 3.8.10

```
import pyBigWig

bw = pyBigWig.open("vafator/tests/resources/best.seg.minimal.bed", "w")
bw.addEntries(['1', '1', '1'], [100, 200, 300], ends=[200, 300, 400], values=[1.2, 1.3, 1.4])
```

**Comment by dpryan79** [comment]
@priesgo You need to add the bigWig header first: https://github.com/deeptools/pyBigWig#add-a-header-to-a-bigwig-file

**Comment by priesgo** [comment]
I see now! Thanks!
