### ISSUE TITLE
library import error

### ISSUE THREAD

**Issue by chanwkimlab** [deeptools/pyBigWig#130]
Hi,
When I called `import pyBigWig`, I encountered the following error message:
```
ImportError: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```
Could you please help me resolve this error?

Thanks,
Chanwoo

**Comment by dpryan79** [comment]
How did you install pyBigWig? It actually doesn't directly link against openssl, so this must be improper linking of some dependency.

**Comment by chanwkimlab** [comment]
Thank you for your quick reply. I installed pyBigWig using the `pip install pyBigWig` command.

**Comment by dpryan79** [comment]
Unfortunately this error appears to be in a dependency somewhere (almost certainly `curl`) and will prove difficult to diagnose. I suggest installing with conda instead.

**Comment by chanwkimlab** [comment]
Installing with `conda install pyBigWig` resolved the issue. Thank you for your suggestion!
