### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eh2hv2_s/pyBigWig/

### ISSUE THREAD

**Issue by sandunr** [deeptools/pyBigWig#51]
Hi,

I keep getting this error when i try to install pybigwig on my ubuntu machine with the following command 'pip install pyBigWig==0.3.2'.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eh2hv2_s/pyBigWig/

and this error with command 'pip install pyBigWig',

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pp2reo0g/pybigwig/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bxqpelh1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pp2reo0g/pybigwig/

Any idea why this is happening?

Thanks,
Sandun

**Comment by dpryan79** [comment]
No clue, though there's no reason to use an old version.

**Comment by dpryan79** [comment]
There's a suggestion [from here](https://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c) that setuptools may be incorrectly installed.
