### ISSUE TITLE
type="sum" for bw.stats()

### ISSUE THREAD

**Issue by tturowski** [deeptools/pyBigWig#52]
Hi,
An additional type='sum' for bw.stats() would be very useful

**Comment by dpryan79** [comment]
I'm looking into implementing this now. Am I correct in assuming that you'd want it to produce the sum of the per-base values?

**Comment by tturowski** [comment]
yes - something what would replace: 
`sum(bw.values(gene_name, 0, length))`

**Comment by dpryan79** [comment]
This is now implemented for the next release, which will come out once I get more details on #56
