### ISSUE TITLE
addEntries

### ISSUE THREAD

**Issue by andyjslee** [deeptools/pyBigWig#56]
I get the following error:

> RuntimeError: The entries you tried to add are out of order, precede already added entries, or otherwise use illegal values.

The problem is that I sort my lists and then add the entries.

**Comment by dpryan79** [comment]
Which version are you using and are you using numpy arrays?

**Comment by andyjslee** [comment]
Sorry, I think I know what the problem is.

**Comment by andyjslee** [comment]
Sorry, I do think that there is a problem. Yes, I do use numpy

**Comment by dpryan79** [comment]
Can you give me a small test example that causes the problem and can you ensure you're using version 0.3.10?

**Comment by dpryan79** [comment]
@andyjslee Any update on reproducing this?
