### ISSUE TITLE
Segmentation fault: 11 on MacOS High Sierra 10.13.3

### ISSUE THREAD

**Issue by daquang** [deeptools/pyBigWig#58]
I did a completely fresh install of Anaconda3 and then installed pyBigWig using 

```
conda install -c bioconda deeptools
```

When I ran `import pyBigWig` I got a `Segmentation fault: 11` error.

This issue does not exist on my Ubuntu 16.04 computer.

**Comment by dpryan79** [comment]
Can you check whether the python is coming from conda-forge or the default channel? A simple `conda list | grep python` should produce the information I need (just post the exact python version from that).

**Comment by daquang** [comment]
```
$ conda list | grep python 
ipython                   6.1.0            py36hf612aae_1  
ipython_genutils          0.2.0            py36h241746c_0  
msgpack-python            0.4.8            py36h46767b2_0  
python                    3.6.3                h6804ab2_0  
python-dateutil           2.6.1            py36h86d2abb_1  
python.app                2                py36h7fe2238_6  
```

**Comment by dpryan79** [comment]
Try `conda install -c conda-forge python==3.6.4`. For some reason, there's an incompatibility between the pythons supplied by conda-forge and anaconda for OSX.

**Comment by daquang** [comment]
Seems to have done the trick. Very odd that this issue exists specifically for OSX.

**Comment by dpryan79** [comment]
Agreed, I've tried figuring out exactly why this happens but haven't had much luck.

**Comment by gokceneraslan** [comment]
I also encountered this segfault and I got the same LLDB trace as in this bug: https://github.com/shogun-toolbox/shogun/issues/4068

**Comment by gokceneraslan** [comment]
As also mentioned [here](https://github.com/shogun-toolbox/shogun/issues/4068), the error stems from the fact that pyBigWig is linked dynamically to python library, however the interpreter uses statically linked python. So, if `-undefined dynamic_lookup` linker flag is added (which is added by default, as far as I can see in my builds) and if `python3.6m` is not added to linked libraries, the error goes away. So I managed to make it work with following patch:

```patch
diff --git a/setup.py b/setup.py
index 479cd51..ee50ca5 100755
--- a/setup.py
+++ b/setup.py
@@ -16,15 +16,6 @@ srcs = [x for x in
 srcs.append("pyBigWig.c")

 libs=["m", "z", "curl"]
-if sysconfig.get_config_vars('BLDLIBRARY') is not None:
-    #Note the "-l" prefix!
-    for e in sysconfig.get_config_vars('BLDLIBRARY')[0].split():
-        if e[0:2] == "-l":
-            libs.append(e[2:])
-elif(sys.version_info[0] >= 3 and sys.version_info[1] >= 3) :
-    libs.append("python%i.%im" % (sys.version_info[0], sys.version_info[1]))
-else :
-    libs.append("python%i.%i" % (sys.version_info[0], sys.version_info[1]))

 additional_libs = [sysconfig.get_config_var("LIBDIR"), sysconfig.get_config_var("LIBPL")]
```

@daquang You are using conda-forge python on Mac, right? can you try building pyBigWig with this patch and check if it still works?

**Comment by mooratov** [comment]
Getting a segmentation fault when i did a pip install. It only comes up if i attempt to import a submodule e.g. 
```
>>> import deeptools.utilities
Segmentation fault: 11
```

**Comment by gokceneraslan** [comment]
Are you using macos @mooratov?

**Comment by malizheng** [comment]
I also encountered a similar error. When encountering this "Segmentation fault: 11" exception, "try: except:" cannot recognize this exception, and the program will exit abnormally.  Is there any other way to identify this kind of exception in python?
