### ISSUE TITLE
Unable to open bigBed files

### ISSUE THREAD

**Issue by adelq** [deeptools/pyBigWig#59]
I have been unable to open bigBed files, both local and remote. Opening bigWig files works just fine. Using the example bigBed opening in the documentation, I get the following error:

```
$ python -c "import pyBigWig; pyBigWig.open('ENCFF001JBR.bigBed')"

[bwHdrRead] There was an error while reading in the header!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Received an error during file opening!
```

The bigBed was downloaded successfully and appears normal based on the `bigBedInfo` results:

```
$ bigBedInfo ENCFF001JBR.bigBed

version: 4
fieldCount: 9
hasHeaderExtension: yes
isCompressed: yes
isSwapped: 0
extraIndexCount: 0
itemCount: 602,461
primaryDataSize: 10,164,686
primaryIndexSize: 46,456
zoomLevels: 10
chromCount: 21
basesCovered: 422,391,811
meanDepth (of bases covered): 1.040633
minDepth: 1.000000
maxDepth: 2.000000
std of depth: 0.197439
```

Is there an additional bigBed library I need to have installed? Does opening bigBed files require a substantially greater amount of memory? (currently have ~40 GB available)

**Comment by dpryan79** [comment]
What version of pyBigWig do you have installed (`python -c 'import pyBigWig; print(pyBigWig.__version__)`)?

**Comment by adelq** [comment]
Apparently a really old version, since there isn't a `__version__` attribute on the pyBigWig module, and looking at the installed package it seems like it was version 0.2.8. I just installed 0.3.10, and it seems like bigBed importing works just fine now. Thanks!

**Comment by dpryan79** [comment]
Glad it was such an easy fix :)
