### ISSUE TITLE
RuntimeError: You must supply at least a chromosome!

### ISSUE THREAD

**Issue by iamjli** [deeptools/pyBigWig#63]
`bigwig.stats(chr, start, end)` gives a RuntimeError if `start` and `end` are of type `numpy.int`. This is confusing, since the error message is misleading. 

Would you please fix this issue to allow numpy integers to be passed in? This is quite common, especially for those of us using pandas 🐼 :)

**Comment by dpryan79** [comment]
I can't reproduce this, can you provide an example? Please include the version of python and numpy that you're using.

**Comment by iamjli** [comment]
Sure

![image](https://user-images.githubusercontent.com/7219365/39456524-00e5853a-4cb5-11e8-865e-f11cfcd80c66.png)

**Comment by dpryan79** [comment]
Thanks, I think I was testing with a numpy.int rather than int64.

**Comment by dpryan79** [comment]
This is now supported (as far as I can tell) in the master branch so I'll push out a new release.

**Comment by dpryan79** [comment]
This is now in version 0.3.12
