### ISSUE TITLE
pip install pyBigWig does not work on latest version of Anaconda (5.3, Python 3.7 version)

### ISSUE THREAD

**Issue by daquang** [deeptools/pyBigWig#70]
I am running on Mac OS X Mojave. Here's the error I get:

Collecting pyBigWig
  Using cached https://files.pythonhosted.org/packages/d5/0d/8e2a1edb9524790c6a4d0b70bc800a8e4afee1bc7bdd048c54b8d9cf1c32/pyBigWig-0.3.12.tar.gz
Building wheels for collected packages: pyBigWig
  Running setup.py bdist_wheel for pyBigWig ... error
  Complete output from command /Users/daquang/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-install-yv7gipao/pyBigWig/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-wheel-hr537bj0 --python-tag cp37:
  /Users/daquang/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'classifier'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/test.py -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
  running egg_info
  writing pyBigWig.egg-info/PKG-INFO
  writing dependency_links to pyBigWig.egg-info/dependency_links.txt
  writing requirements to pyBigWig.egg-info/requires.txt
  writing top-level names to pyBigWig.egg-info/top_level.txt
  reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
  copying pyBigWigTest/test.bigBed -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
  copying pyBigWigTest/test.bw -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
  running build_ext
  building 'pyBigWig' extension
  C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daquang/anaconda3/include -arch x86_64 -I/Users/daquang/anaconda3/include -arch x86_64

  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/libBigWig
  compile options: '-DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/Users/daquang/anaconda3/include/python3.7m -I/Users/daquang/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/daquang/anaconda3/include/python3.7m -c'
  gcc: libBigWig/bwRead.c
  gcc: libBigWig/bwValues.cgcc: libBigWig/io.cgcc: libBigWig/bwStats.c
  gcc: libBigWig/bwWrite.c
  gcc: pyBigWig.c

  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrunxcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daquang/anaconda3/include -arch x86_64 -I/Users/daquang/anaconda3/include -arch x86_64 -DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/Users/daquang/anaconda3/include/python3.7m -I/Users/daquang/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/daquang/anaconda3/include/python3.7m -c libBigWig/io.c -o build/temp.macosx-10.7-x86_64-3.7/libBigWig/io.o" failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyBigWig
  Running setup.py clean for pyBigWig
Failed to build pyBigWig
Installing collected packages: pyBigWig
  Running setup.py install for pyBigWig ... error
    Complete output from command /Users/daquang/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-install-yv7gipao/pyBigWig/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-record-w1z6lbxd/install-record.txt --single-version-externally-managed --compile:
    /Users/daquang/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'classifier'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/test.py -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
    running egg_info
    writing pyBigWig.egg-info/PKG-INFO
    writing dependency_links to pyBigWig.egg-info/dependency_links.txt
    writing requirements to pyBigWig.egg-info/requires.txt
    writing top-level names to pyBigWig.egg-info/top_level.txt
    reading manifest file 'pyBigWig.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pyBigWig.egg-info/SOURCES.txt'
    copying pyBigWigTest/test.bigBed -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
    copying pyBigWigTest/test.bw -> build/lib.macosx-10.7-x86_64-3.7/pyBigWigTest
    running build_ext
    building 'pyBigWig' extension
    C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daquang/anaconda3/include -arch x86_64 -I/Users/daquang/anaconda3/include -arch x86_64

    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/libBigWig
    compile options: '-DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/Users/daquang/anaconda3/include/python3.7m -I/Users/daquang/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/daquang/anaconda3/include/python3.7m -c'
    gcc: libBigWig/bwRead.c
    gcc: libBigWig/bwStats.cgcc: libBigWig/io.c
    gcc: libBigWig/bwValues.c
    gcc: libBigWig/bwWrite.c

    gcc: pyBigWig.c
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrunxcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daquang/anaconda3/include -arch x86_64 -I/Users/daquang/anaconda3/include -arch x86_64 -DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/Users/daquang/anaconda3/include/python3.7m -I/Users/daquang/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/daquang/anaconda3/include/python3.7m -c libBigWig/bwWrite.c -o build/temp.macosx-10.7-x86_64-3.7/libBigWig/bwWrite.o" failed with exit status 1

    ----------------------------------------
Command "/Users/daquang/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-install-yv7gipao/pyBigWig/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-record-w1z6lbxd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/pip-install-yv7gipao/pyBigWig/

**Comment by dpryan79** [comment]
You appear to have some random issue with your build environment that falls outside the purview of pyBigWig. Since you're already using conda, simply `conda install -c conda-forge -c bioconda pybigwig`.

**Comment by daquang** [comment]
It works now! Thanks!

**Comment by dpryan79** [comment]
Thanks for the quick follow-up!
