### ISSUE TITLE
libcurl3/4 issue on Ubuntu machine

### ISSUE THREAD

**Issue by oristaszewski** [deeptools/pyBigWig#73]
This is an ongoing problem with many packages with a transition from libcurl3 to libcurl4 in Ubuntu: deeptools does not run due to:
ImportError: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/lib/python2.7/dist-packages/pyBigWig.so)

is there a way to fix this other than reverting to libcurl3 (and breaking a host of mostly R packages in the process)?

**Comment by dpryan79** [comment]
Try reinstalling pyBigWig. I didn't write it to be dependent on any particular version of curl, so if you upgraded and the previously linked-to version of libcurl is now gone then that should solve the problem.

BTW, you could also use conda and its environments and not have to deal with this.
