### ISSUE TITLE
ImportError:  ndefined symbol: PyInt_Check

### ISSUE THREAD

**Issue by nlapalu** [deeptools/pyBigWig#78]
Hi,

I have got this error:  

```
File "./transcriptome.py", line 6, in <module>
    import pyBigWig
ImportError: /usr/local/lib/python3.4/dist-packages/pyBigWig.cpython-34m.so: undefined symbol: PyInt_Check
```

Problem with python 3.4 ?

**Comment by nlapalu** [comment]
From https://docs.python.org/3/howto/cporting.html

Python 3 has only one integer type, int(). But it actually corresponds to Python 2’s long() type—the int() type used in Python 2 was removed. In the C-API, PyInt_* functions are replaced by their PyLong_* equivalents.

**Comment by dpryan79** [comment]
Is there a reason you're using such an old version of python 3? I stopped testing on python 3.4 a year or so ago, at least at that point pyBigWig still worked on it.

**Comment by dpryan79** [comment]
BTW, all of the instances of `PyInt_Check` in the code are only used in python 2, so I suspect something odd happened when pyBigWig got installed and python told C that python 2 was being used.

**Comment by nlapalu** [comment]
Python3.4 is my default python3 on ubuntu 14.X.  pyBigWig works now with my personal install of Python3.7.
