### ISSUE TITLE
Declare versioned dependency on libBigWig instead of copying

### ISSUE THREAD

**Issue by smoe** [deeptools/pyBigWig#84]
Hello,

I understand there is a trend to have all source code together that is required for a project. But is there a chance to just reference a version of libBigWig that pyBigWig wants and leave that dependency's installation to the user? To keep it very close to how your code and development workflow is today, you could have libBigWig as a git subproject.

This is an issue for me since I am packaging rseqc for Debian+Ubuntu that has your software as a dependency. I have already prepared a package for libBigWig and would happily see your project link against that official version instead of your local copy. No need for you to adapt this, fyi only, this technically seems to works (all your tests passing) with a cute patch (https://salsa.debian.org/med-team/python-pybigwig/blob/master/debian/patches/prepareForExternalLibBigWig.patch) against setup.py.

The benefit for everyone would be some extra confidence that there is no change to the C implementation in pyBigWig when there is an error. And there should not need to a need for an update of pyBigWig when there is a new version of libBigWig out either.

Cheers,

Steffen

**Comment by dpryan79** [comment]
The primary reason I rolled libBigWig into pyBigWig is so people can `pip install` it, which doesn't work if I make it a system dependency. I can try to add some official documentation about the requirements of the underlying version to give you some peace of mind, of course.

As an aside, do people still use apt to install bioinformatics packages? We (biostars and stackexchange) have been strongly encouraging people not to do that for a number of years now, especially now that people have transitioned to using conda environments.

**Comment by smoe** [comment]
> The primary reason I rolled libBigWig into pyBigWig is so people can `pip install` it, which doesn't work if I make it a system dependency. I can try to add some official documentation about the requirements of the underlying version to give you some peace of mind, of course.

I had not thought about pip, admittedly, and neither do I know enough about it to make any suggestions.  Yes, some formal spec of requirements would be great! Many thanks!

> As an aside, do people still use apt to install bioinformatics packages? We (biostars and stackexchange) have been strongly encouraging people not to do that for a number of years now, especially now that people have transitioned to using conda environments.

I use conda myself in our HPC environment. For everything else - not. Conda is great, especially since packages are created more easily and independently across many channels, and you have parallel installs when there are version incompatibilities. And you have everything cross platforms, too. My end is more like having my Mac as the MS-Word machine with Virtualbox offering Debian. When mixing Conda with installations from other sides - be it via pip or from what Debian provides, there may be complications. So I can see where you are coming from when directing users to something that you know to just work.

My pitch for Debian
 * if it happens to have (https://blends.debian.org/med/tasks/bio) what you want then it should be great and demand minimal resources
   * very quickly set up (say in the cloud)
   * very quickly removed (say on your laptop)
 * we keep experimenting - like with links to registries (bio.tools et al.) and the EDAM ontology
 * snapshot.debian.org allows to go back in time (compare scientific results, extend past projects, ...)
 * outreach
   * to anyone knowing how to install software on Debian/Ubuntu
   * school kids / pensioneers may more easily find an interest in the science
   * the package descriptions are translated to many languages
 * beauty
   * all the complications of Debian packaging typically have a technical motivation
   * when Debian runs into problems because of version conflicts/compiler problems, we try fixing them, or report them at least, which may help the community

I should probably work on my pitch a bit more. PyBigWig is referenced by a nf-core workflow (https://github.com/nf-core/rnaseq/blob/master/environment.yml) . We are currently packaging these and bcbio. Together with Debian's Continuous Integration testing on associated test data, I expect the community to eventually trust these packages as much as everyone trusts the distribution's core tools. I have no exact idea what workflows Debian will cover. There are a few that will come to have that Linux distribution natively support the sequencing/analysis of DNA and those will be as solid as it gets. And then it will all depend on the community like yours (should say "ours").
