### ISSUE TITLE
Segfault when trying to access a non-existing header

### ISSUE THREAD

**Issue by pbenner** [deeptools/pyBigWig#88]
>>> import pyBigWig
>>> bw = pyBigWig.open("some_file_that_does_not_exist.bw", "w")
>>> bw.header()
/usr/bin/python3: line 2: 42653 Segmentation fault      (core dumped) prun python3 "$(basename "$0")" "$@"

**Comment by dpryan79** [comment]
Hmm, yeah, I should really have it die more gracefully than that!
