### ISSUE TITLE
How to install pyBigWig in windows?

### ISSUE THREAD

**Issue by burcakotlu** [deeptools/pyBigWig#98]
Hi, I'm getting the error below while installing pyBigWig on windows.
Is there a way to solve it?

C:\Users\burcak\Anaconda3>pip install  pyBigWig
Collecting pyBigWig
  Using cached https://files.pythonhosted.org/packages/b0/e2/cf945d541a10bb9c675f986d5bf0b0268544721054d17cc6260cfcfb3685/pyBigWig-0.3.17.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\burcak\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\burcak\\AppData\\Local\\Temp\\pip-install-0iih0ohf\\pyBigWig\\setup.py'"'"'; __file__='"'"'C:\\Users\\burcak\\AppData\\Local\\Temp\\pip-install-0iih0ohf\\pyBigWig\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\burcak\AppData\Local\Temp\pip-install-0iih0ohf\pyBigWig\pip-egg-info'
         cwd: C:\Users\burcak\AppData\Local\Temp\pip-install-0iih0ohf\pyBigWig\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\burcak\AppData\Local\Temp\pip-install-0iih0ohf\pyBigWig\setup.py", line 24, in <module>
        for e in sysconfig.get_config_vars('BLDLIBRARY')[0].split():
    AttributeError: 'NoneType' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dpryan79** [comment]
I honestly have no clue, presumably you would need to use the linux subsystem on Windows 10. This particular problem I could fix in the code, but I fully suspect that there would be many issues installing dependencies on Windows.

**Comment by dpryan79** [comment]
For reference one can use WSL or WSL2 on windows. There's no other specific support for it.
